---

CONVERSATION_LOGS: # implementation: save conversational logs for debugging
    save: False
    nlp: True
    path: reports/conversations/

DATA:
  ontology_path: data/movies_ontology.json
  db_path: data/movies_dbase.db
  slot_values_path: data/slot_values.json

NLU:
  tag_words_slots: config/tag_words_slots.json

TELEGRAM: True # execute the code on Telegram

POLLING: True # True when using Telegram without server

MESSENGER_MODE: False

MESSENGER: False

WEBHOOK_URL: <<URL>> # end url with "/"

BOT_TOKEN_PATH: config/bot_token.yaml

BOT_HISTORY: # save the conversational logs for Telegram users
    save: True
    path: conversation_history/